name: Test artifact upload

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p /tmp
    - run: echo hello > /tmp/world.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /tmp/world.txt
