name: unit tests

on: 
  pull_request:

  push:
    branches:
      - 'release-*'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changed-files:
     uses: ./.github/workflows/changed_files.yaml
  test-calculator:
    runs-on: ubuntu-latest
    needs: changed-files
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
        check-latest: true
    - run: echo ${{ needs.changed-files.outputs.non-markdown-files }}
    - name: Test code
      run: cd calculator && go test -v
 